# Generated by Django 4.0.2 on 2022-02-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_alter_athlete_plan_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
