# Generated by Django 4.0.2 on 2022-02-08 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_benficiary', to='athletes.athlete'),
        ),
    ]
