# Generated by Django 4.0.2 on 2022-02-08 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_payment_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='beneficiary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletes.athlete'),
        ),
    ]
