# Generated by Django 4.0.2 on 2022-02-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_athlete_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
