# Generated by Django 4.0.2 on 2022-02-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_athlete_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
