# Generated by Django 4.0.2 on 2022-02-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0009_alter_athlete_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
